from aiogram.dispatcher.filters.state import StatesGroup, State


class test_2(StatesGroup):
    answer1 = State()
    answer2 = State()
    answer3 = State()
    answer4 = State()
    answer5 = State()
    answer6 = State()
    answer7 = State()
    answer8 = State()
    answer9 = State()
    answer10 = State()
    answer11 = State()
    answer12 = State()
    answer13 = State()
    answer14 = State()
    answer15 = State()
    answer16 = State()
    answer17 = State()
    answer18 = State()
    answer19 = State()
    answer20 = State()
    answer21 = State()
    answer22 = State()
    answer23 = State()
    answer24 = State()
    answer25 = State()
    answer26 = State()
    answer27 = State()
    answer28 = State()
    answer29 = State()
    answer30 = State()
    answer31 = State()
    answer32 = State()
    answer33 = State()
    answer34 = State()
    answer35 = State()
    answer36 = State()
    answer37 = State()
    answer38 = State()
    answer39 = State()
    answer40 = State()
